### ISSUE TITLE
Code Review for Von

### ISSUE THREAD

**Issue by Galope-Jhean** [PUP-BSIT/ex9-tuf_developers#1]
Hello Von, as per our discussion, here are the things to consider in your directory

- [x] **Having a clean directory**
  - [store images and other assets in a folder named images or assets]( https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g26e9a7bd30a_1_0)
  - It is ideal to have only your main HTML and your main CSS (if one only) to be the only ones directly inside the folder
  - once adapted your directory should look something like this: 
   
     ![image](https://github.com/PUP-BSIT/ex9-tuf_developers/assets/96009163/0eeafb5b-82a8-4191-8b57-149ba90145b6)

- [x] **Concising Styles**
   - It would be better to group all elements with the same styling instead of repeating it
 https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/vonryan.css#L123-L130
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/vonryan.css#L132-L138
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/vonryan.css#L140-L146
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/vonryan.css#L148-L153

   All the classes mentioned above have similar styling it would be much more efficient to make it as concise as possible 

- [x]  **Make use of the alt attribute**
   - Lines mentioned below could use some good alt attribute 
   https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L62-L67
   - It is good practice, provides accessibility, and could help with SEO. Check out this [article](https://www.semrush.com/blog/alt-text/).

- [x]  **Mobile First Development**
    - Upon development, it would be nice to start at the mobile view and gradually scale up to larger screen sizes. 
    - This approach allows us to focus on the most critical aspects of the user interface and functionality for mobile users, ensuring that the site is responsive and performs well on smaller screens. 
    - This ensures a smooth and efficient development process while prioritizing the user experience on mobile devices, which are often the first point of contact for many users.

- [x]  **Unessecary Spaces on HTML File**
   - This is just a personal preference of mine, ignore it if you would like

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L8

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L13

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L25

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L58

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L70

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L79

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L84

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L89

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L95

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L100

    https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/nogadas_vonryan/nogadas_vonryan.html#L105

   The empty spaces mentioned above seem unnecessary.

Overall you did a great job. Your code demonstrates a commendable level of detail and clarity. Its structure is well-organized, facilitating easy comprehension. Descriptive variable names significantly contribute to its readability, making it even more accessible.

**Comment by nogadas-vonryan** [comment]
- #8 
Thank you po!
