### ISSUE TITLE
Code Review for Donatas 

### ISSUE THREAD

**Issue by Naoe-Adrian** [PUP-BSIT/ex9-tuf_developers#2]
_Just fill up the check box once you're done thank you so much <3_
- [x] Project Structuring

Organize all your images and other HTML files into a single asset folder. You can name it 'image' or 'asset'. For HTML files related to your projects, consider creating a folder named 'works'. 

_don't forget to modify the file pathing of your codes after you make folders_

This will significantly improve the organization of your project
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g26e9a7bd30a_1_0

it can be like this 
![image](https://github.com/PUP-BSIT/ex9-tuf_developers/assets/115059074/dda86929-13b0-4629-8fd2-ade0a915be00)

- [x] **1.Broken Link avoidance**

It is currently functional, but there's a risk of encountering a broken link. I recommend changing the href attribute to href="./practice_1.html" to ensure a relative path. Also consider  the use of target="_blank" to prevent users from navigating away from the landing page.
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/donatos_andrea/donatos_andrea.html#L24-L28

_it can be like this_

`<a href="./practice_1.html" target="_blank">Practice 1</a>`

- [x] **2.Naming convention**

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5
When naming classes, choose descriptive names. 

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/donatos_andrea/donatos_andrea.html#L50

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/donatos_andrea/donatos_andrea.html#L55
For example, when assigning a class name to your div : 
instead of using class="bodyy", class="label" consider using 'details-container' or any other name that reflects its purpose, function, or content.

_It can be like this_
`<div class="form-label">
`
`<div class="details-container"> ` 

When assigning IDs, consider using more descriptive names, especially when it's a single word. For instance, instead of 'subj', 'msg' and 'smcm', consider using 'subject','message' and 'send_copy' for clarity."
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/donatos_andrea/donatos_andrea.html#L60-L61

_It can be like this_
```
<div class="form-label">
    <label for="full-name">Full name</label>
    <input type="text" name="full_name" id="full_name" />
</div>
```

to avoid this line of code 
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/donatos_andrea/andrea.css#L73

- [x] **3.Delete unnecessary body tags in your html**

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/donatos_andrea/donatos_andrea.html#L51

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/donatos_andrea/donatos_andrea.html#L84

- [x] **4.Remove unnecessary comments**

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/donatos_andrea/andrea.css#L43

- [x] **5.User alt atribute** 
alt attribute within the image tag provides alternative text for the image. This text serves two important purposes: accessibility and SEO. For users with visual impairments who rely on screen readers.
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/donatos_andrea/donatos_andrea.html#L41-L46

it can be like this
`<img src="picture_1.jpg" alt="picture of thing"/>`
Also don't forget to customize your CSS code if you change your class and id names to update your webpage design

**Comment by Naoe-Adrian** [comment]
This is optional but it can be beneficial in your webdev journey, I like the simplicity of your website the use of paper theme and retro background is good.

You navigate on this website to check some inspiration: https://www.behance.net/


_This one is similar theme on your website you can check this_
https://www.behance.net/gallery/189542863/Vintage-Clothing-Website

You can remove this shadow if you want because its not visible anymore in your website due to its background
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/donatos_andrea/andrea.css#L64

Adding margins can also help prevent overlapping between input fields and divs. If you have some time, you may find it beneficial to watch video tutorials like this : https://www.youtube.com/watch?v=t43GBXC40fo&list=PLP2PxLLwJa_sYR0_4GYvKDsPjrQ0qjtTH 

![image](https://github.com/PUP-BSIT/ex9-tuf_developers/assets/115059074/3d89c223-6219-4e2f-b473-37e6a4044c31)

To improve readability, align the checkbox in the 'Send me a copy' section by adjusting the div properties of your form in your CSS.

![image](https://github.com/PUP-BSIT/ex9-tuf_developers/assets/115059074/3c4264d2-83c7-4c65-840e-58a03a671f66)

_You can imitate this kind of layout of form_
![image](https://github.com/PUP-BSIT/ex9-tuf_developers/assets/115059074/2295f41f-7d94-41ad-a876-071095e8a7b9)



Learning to code can be challenging, but with dedication and practice, you can achieve amazing things.  I really like your website overall!  If you have any questions or need help with anything, don't hesitate to reach out.

**Comment by Donatos-Andrea** [comment]
- #7  
Thank you.

**Comment by Naoe-Adrian** [comment]
I see how you improve your website! The use of green scheme is eye pleasing. Also your form section is responsive unlike last time! Big improvement. Keep iTUF ❤️.
