### ISSUE TITLE
Code Review for Roche

### ISSUE THREAD

**Issue by Dimasacat-Andronicus** [PUP-BSIT/ex9-tuf_developers#3]
Code Review for Roche's Folder.
Check the boxes if you're done with it.

- [x] Group the images in a same folder. Group the html pages in a same folder.
 Your folder is messy, make a folder for images and folder for html files except your main html to be organize.
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g26e9a7bd30a_1_0

- [x] Might cause Broken Link
I suggest you make it `<link rel="stylesheet" href="./mauijane.css" />`
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/roche_mauijane/roche_mauijane.html#L3

- [x] Use Alt Attribute.
It is better to add an attribute "alt" in case your image doesn't load or too long to load.
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/roche_mauijane/roche_mauijane.html#L46-L50

- [x] Your css style in class "title".
It must have space before open curly brace and a space after the selector.
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/roche_mauijane/mauijane.css#L64-L67
Please see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35

- [x] Apply proper indentation of your Selectors.
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/roche_mauijane/mauijane.css#L67-L120
Please see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50

- [x] 'screen' in media query.
You don't need to code 'screen' in media query.
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/roche_mauijane/mauijane.css#L116
Please see this for the example: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g28d48e53e08_0_0

- About applying proper naming convention.

Much better to use descriptive name. I suggest of using other meaningful terms. For example, what class and what container is that?
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/roche_mauijane/roche_mauijane.html#L11
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/roche_mauijane/roche_mauijane.html#L56-L57
Please see: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

- In your Website CSS layout, the "send me a copy" and its checkbox is not properly style. You can alter your code to make it look good. Also, it is much better to make your website mobile first so that it is not that hard to adjust the code for screen size. Additionally, your website's color contrast is a little too bright. To blend the color contrast, add some darker hue. 

- Always remember to remove unnecessary comments. Use it only if your code is unique or difficult to read.

Lastly, always review your own code just to be sure it's good to go.

**Comment by Roche-MauiJane** [comment]
- #10 
Thankyou po!
