### ISSUE TITLE
Code Review for Cahigan

### ISSUE THREAD

**Issue by Odrunia-Mark-Ryan** [PUP-BSIT/ex9-tuf_developers#4]
- [x]  1. Section naming: 
I suggest renaming your sections based on what's its content would be beneficial to you and may help you understand easily what it's content. and make your code more readable.

sample:
`<div id="section 1"> to <div id="interests">`

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/cahigan_marklouie.html#L12

- [x]  2. Splitting elements to multiple lines:
You could split the elements into multiple lines, but when splitting the elements into multiple lines, 
make sure that the continuation line is indented.

reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g29e6ce31160_0_11

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/cahigan_marklouie.html#L74

- [x]  3.  id rename:
I suggest renaming your id's based on what it's purpose/content

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/cahigan_marklouie.html#L60

- [x]  4. space between the numeric value and the unit:
There should not be a space between the numeric value 
and the unit in the border property. It should be 5px instead of 5 px.

sample:
`border :5 px; to border: 5px;`

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/mark_louie.css#L13

- [x]  5.  In your css files, add a space after the selector:

sample:
`#content_1{ to #content_1 {`

reference:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/mark_louie.css#L1
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/mark_louie.css#L6
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/mark_louie.css#L12
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/mark_louie.css#L17
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/mark_louie.css#L21
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/mark_louie.css#L26
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/mark_louie.css#L30
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/work_1.css#L1
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/work_1.css#L12
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/work_1.css#L19
https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/work_2.css#L1

**Comment by Odrunia-Mark-Ryan** [comment]
Suggestions:
1. The brightness of your personal website's color scheme is excessive. 
I recommend changing and limiting the palette to atleast three colors 
for the entire site. Utilizing a color wheel could assist you in 
selecting colors that harmonize well together.

you could also use these links to enhance the color palette of your website:
https://vanschneider.com/colors?ref=inspectresource.com
https://colorhunt.co/?ref=inspectresource.com

2. I suggest to choose another color for your form background in 
your "contact me" section so that your form could be emphasized better.

https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/cahigan_marklouie/cahigan_marklouie.html#L70-L108

https://bootstrapstudio.io/docs/contact-form.html
![contact-form-example](https://github.com/PUP-BSIT/ex9-tuf_developers/assets/138759331/f0b34de8-b345-4e02-a0f8-97563ec44b17)

It's fantastic to see your dedication to web development!  The progress you're making is awesome, and it's clear you're putting in the hard work. Web development is a challenging but rewarding field, and there's so much to learn and create.  Keep at it, and I have no doubt you'll not only develop some amazing skills but also find a deep sense of satisfaction in what you build.

**Comment by go-christianharrel** [comment]
This GitHub Issue is already resolved. I linked the [Pull Request](https://github.com/PUP-BSIT/ex9-tuf_developers/pull/12) that resolved this.
