### ISSUE TITLE
Code Review for Anonuevo

### ISSUE THREAD

**Issue by go-christianharrel** [PUP-BSIT/ex9-tuf_developers#5]
### Required
- **Clean Repository Organization**
  - [x] Consolidate assets into a common folder to avoid clutter in the project directory.
  ![image](https://github.com/PUP-BSIT/ex9-tuf_developers/assets/51312012/c9fc6180-d218-4d99-b4d7-c774a55d8401)
       [View Guidelines](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1pphsWlliw0L_vbPJKbRCpW81Gt151vhOUq4iEw0Ftms7GjjedbKMX-fI_aem_AaHDPId1LpnIKTLO8jtJYQQGefS9ZBVU9dr1OCxS88dCO9DgcNB0UTMObNs4Ok6LM47wdHt4CyLzGnWZQJ0fiCb9#slide=id.g26e9a7bd30a_1_0)
   - [x] All files should be named in snake case, all lowercase. Please rename your `ex9-tuf_developers/anonuevo_jheferson/jhefstyle.css` file to `jhef_style.css` or choose a more descriptive and straightforward filename like `style.css`.
          [View Guidelines](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1pphsWlliw0L_vbPJKbRCpW81Gt151vhOUq4iEw0Ftms7GjjedbKMX-fI_aem_AaHDPId1LpnIKTLO8jtJYQQGefS9ZBVU9dr1OCxS88dCO9DgcNB0UTMObNs4Ok6LM47wdHt4CyLzGnWZQJ0fiCb9#slide=id.g25d18931cb7_3_0)

- **Readability in CSS Selectors**
  - [x] Separate CSS blocks with a single space 
           - also add a single space after selectors and before "{" which is not implemented on your current code.
  https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/anonuevo_jheferson/jhefstyle.css#L110-L117 [View Guidelines](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35)

- **Remove Unnecessary Comments**
  - [x] Eliminate redundant or unnecessary comments.
  https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/anonuevo_jheferson/jhefstyle.css#L109 [View Guidelines](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5)

- **Proper Indentation**
  - [x] Ensure consistent and proper indentation.
  https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/anonuevo_jheferson/jhefstyle.css#L119-L160 [View Guidelines](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50)

**Comment by go-christianharrel** [comment]
### Suggestions (Optional)
- **Use a Single Font Family with a Fallback**
  Specify only one font family with a fallback to sans-serif.
  https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/anonuevo_jheferson/jhefstyle.css#L7-L12
  Eliminate unnecessary font family declarations.
  https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/anonuevo_jheferson/jhefstyle.css#L30

I suggest you to use sans serif as fall back:
```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: Verdana, sans-serif;
}
```
### HTML & CSS Refactoring
 **Refactor HTML and CSS for Improved Readability**
  - Simplify class usage in HTML and CSS.
  https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/anonuevo_jheferson/anonuevo_jheferson.html#L64
  Implement recommended layout adjustments for forms:

```html
<!-- HTML -->
<div class="form">
  <h2>Contact Me</h2>
</div>

```
```css
/* CSS */
.form h2 {
  text-align: center;
} 
```

### By familiarizing yourself more with these techniques, you'll be better prepared to answer questions or implement them when necessary. 

- **before pseudo-element** 
   https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/anonuevo_jheferson/jhefstyle.css#L85
- **CSS counters** 
   https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/anonuevo_jheferson/jhefstyle.css#L80-L89
- **nth-child selector** 
  https://github.com/PUP-BSIT/ex9-tuf_developers/blob/1f0add269054924241347e881d787ec0abc053a9/anonuevo_jheferson/jhefstyle.css#L130-L133
       you might also consider simplifying this nth-child selector

**Comment by go-christianharrel** [comment]
### Suggested Webpage Design

![image](https://github.com/PUP-BSIT/ex9-tuf_developers/assets/51312012/b6ff486e-cace-4416-93b0-2cecdba1b9f5)
### Suggested CSS for Form
```css
/* MY CSS FOR THE FORM */
.form {
  max-width: 600px;
  margin: 0 auto;
}

.container {
  display: grid;
  gap: 15px;
}

.upper {
  display: grid;
  gap: 15px;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
}

.upper > div:nth-child(1),
.upper > div:nth-child(2) {
  grid-column: span 1;
}

label {
  font-weight: bold;
}

input[type="email"],
input[type="text"],
input[type="number"],
textarea {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 5px;
  box-sizing: border-box;
}

.checkbox-container {
  display: flex;
  align-items: center;
}

.checkbox-container input[type="checkbox"] {
  margin-right: 5px;
  margin-left: 10px;
}

.checkbox-container label {
  font-weight: normal;
}

.message-container textarea {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 5px;
  box-sizing: border-box;
  resize: none;
}

.submit-container {
  margin-top: 15px;
}

.submit-container input[type="submit"] {
  padding: 10px 20px;
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  font-size: 16px;
  transition: background-color 0.3s ease;
}

.submit-container input[type="submit"]:hover {
  background-color: #0056b3;
}

---

**Comment by go-christianharrel** [comment]
Your coding style closely mirrors mine, making it challenging to pinpoint errors or enhancements in your code, but nonetheless, it was an enjoyable experience. I appreciate your effort in implementing a consistent style across containers or classes to minimize style redundancies. Consider removing the unnecessary IDs and ensuring consistency between class and ID usage: classes for CSS styling and IDs for JavaScript functionality. I apologize for publishing this issue delayed, @anonuevo-jheferson. I hope you have learned something from this issue. Thank you! :heart:

**Comment by Anonuevo-Jheferson** [comment]
> Your coding style closely mirrors mine, making it challenging to pinpoint errors or enhancements in your code, but nonetheless, it was an enjoyable experience. I appreciate your effort in implementing a consistent style across containers or classes to minimize style redundancies. Consider removing the unnecessary IDs and ensuring consistency between class and ID usage: classes for CSS styling and IDs for JavaScript functionality. I apologize for publishing this issue delayed, @anonuevo-jheferson. I hope you have learned something from this issue. Thank you! ❤️

thank you po!
